# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcapi', '0002_auto_20160223_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
